Repository gaseous-project/hasheous, pull requests merged in 2025-02, with the labels that each got.

#115 Update en.json
  hasheous/wwwroot/localisation/en.json
Labels: documentation

#117 Add RetroAchiements support
  hasheous/Classes/Config.cs
  hasheous/Classes/DataObjects.cs
  hasheous/Classes/Metadata/Communications.cs
  hasheous/Classes/Metadata/RetroAchievements/MetadataDownload.cs
  hasheous/Classes/Metadata/RetroAchievements/MetadataGameHashesModel.cs
  hasheous/Classes/Metadata/RetroAchievements/MetadataGameModel.cs
  hasheous/Classes/Metadata/RetroAchievements/MetadataPlatformModel.cs
  hasheous/Classes/ProcessQueue.cs
  hasheous/Classes/SignatureIngestors/XML.cs
  hasheous/Classes/SignatureManagement.cs
  hasheous/Models/DataObjectItem.cs
  hasheous/Models/Signatures_Games.cs
  hasheous/Program.cs
  hasheous/Schema/hasheous-1014.sql
  hasheous/hasheous.csproj
  hasheous/wwwroot/fonts/Lato-Bold.ttf
  hasheous/wwwroot/fonts/Lato-Light.ttf
  hasheous/wwwroot/fonts/Lato-Regular.ttf
  hasheous/wwwroot/localisation/en.json
  hasheous/wwwroot/pages/dataobjectdetail.js
  hasheous/wwwroot/pages/dataobjectedit.js
  hasheous/wwwroot/pages/romdetail.js
  hasheous/wwwroot/scripts/common.js
  hasheous/wwwroot/styles/dark.css
  hasheous/wwwroot/styles/light.css
  hasheous/wwwroot/styles/style.css
Labels: enhancement

#118 Resolve an error in the SQL upgrade script
  hasheous/Schema/hasheous-1014.sql
Labels: bug

#119 Bug fixes, and minor UI updates
  hasheous/Classes/DataObjects.cs
  hasheous/Controllers/V1.0/DataObjectController.cs
  hasheous/wwwroot/index.html
  hasheous/wwwroot/localisation/en.json
  hasheous/wwwroot/pages/dataobjectdetail.html
  hasheous/wwwroot/pages/dataobjectdetail.js
  hasheous/wwwroot/pages/dataobjects.js
  hasheous/wwwroot/pages/search.js
  hasheous/wwwroot/pages/sources.html
  hasheous/wwwroot/pages/sources.js
  hasheous/wwwroot/scripts/dataobjects.js
  hasheous/wwwroot/styles/dark.css
  hasheous/wwwroot/styles/light.css
  hasheous/wwwroot/styles/style-skinny.css
  hasheous/wwwroot/styles/style.css
Labels: bug, enhancement

#121 Provide links to Open Collective, and TOS updates
  .github/funding.yml
  hasheous/wwwroot/images/donate.svg
  hasheous/wwwroot/index.html
  hasheous/wwwroot/localisation/en.json
  hasheous/wwwroot/pages/home.html
Labels: documentation
